#!/usr/bin/env bash

docker build -t tupy-docker .
docker run --name tupy-dev \
           --rm \
           -v "$PWD/v5-unity":/opt/app \
           -w /opt/app \
           -i \
           -p 8003:8003 \
           -t tupy-docker \
           sh -c "yarn install; \
                  pip3 install -r requirements.txt; \
                  sh"
